i18n.json
server.js

This pull request changes the confirmation comment to match the new format specified by Snorrlax in #32.
I haven't tested this (not sure how to) and I'm a bit of a javascript beginner, so I make no guarantees that this will work. I've done my best to make sure there are no syntax errors, but I may have missed something.

Update format of confirmation comment

---

README.md
RedditAPIDriver/index.js

Took me a while to realize one of my problems - with respect to wiki creation errors from the bot - was just because I hadn't enabled the wiki in my subreddit, which was disabled by default; oops.  A lot of the debug stuff was done before that, but I've still been working with & improving that as I go and try to get the bot to be able to send messages to people anyway.

Update readme to mention subreddit settings, improve debug output

---

.gitignore
package.json
server.js

Added snoowrap to package.json and .idea folder to .gitignore (to ignore webstorm folder)
Added semi-colons to lines.
Started to add comments to server.js and added 'use strict' to the top
Hit a snag with the comments, waiting for clarification but will move on to implementing snoowrap.

Some minor changes but I didn't want to get too far ahead.

---

README.md
RedditAPIDriver/index.js
delta-boards-three/index.js
i18n.json
package.json
server.js

Fairly straightforward.  Notes: I didn't bother rebasing without changes from #55.  Didn't seem necessary, I assume you'd merge that first.  When I tested, I actually tested with the critical check being `flairCount >= 0` rather than `flairCount === 1`.  Based on my read of the wiki update fn, this should work, but it takes me a fair bit of time to test with all the rate--limiting that reddit applies.

Send first time users a welcome message after being awarded delta #14

---

.babelrc
entry.js
get-wiki-content.js
lib/.gitignore
package.json
server.js

Also added path.join, so that the file reads don't use a relative path that would break when moving the built file to ./lib/. Prep for issue #49

#63: Replace requires with fs.readFileSync in prep for browserify

---

README.md

Added DB stickied comment to roadmap

docs(readme): update readme with latest priorities

---

src/delta-boards-three.js

Bug: Only included in weekly statistic if in the same month ( issue #78)

---

README.md
package.json
yarn.lock

MystK - just a few quick updates for things that seemed a little out of sync.  I believe these three make sense since you have a `yarn.lock` file in the repo, but no worries if not.
(Note on changes to `yarn.lock`: all I did was `npm install -g yarn` && `yarn` - I'm guessing I got a newer version of yarn that handles things a little differently, hence the changes.  A lot of the changes look like it's just specifying the multiple ranges a given version of a library is able to satisfy)

Minor infrastructure updates

---

package.json
src/index.js

This should replace the `&amp;` with a normal `&`.

Fixed issue 135

---

README.md

Checked the box for edited comments and added the 3 minutes issue. I put it at the top since I think it's the highest priority.

docs(readme): Update roadmap

---

src/delta-boards-year.js

Credentials were not correctly accessed, they are now. Also the start and end date were not always correct so I fixed that too.

Fix for Yearly deltaboard

---

src/delta-boards-three.js
src/delta-boards-year.js
src/utils.js

feat(deltaboard): add separate update times to each board

---

src/delta-boards-three.js

Changed from ** Daily ** to ## Daily, etc.

fix(deltaboards): Change titles

---

src/index.js

Fixed the wrong dbReplied usage, should now work as intended.

fix(doubleDeltaCommets): reapplied fix for #28 from pull request #145

---

src/index.js

Per the issue mentioned in the commit. 
Please forgive the unnecessary pull request.

Adjusted the wording on the top of delta history

---

README.md

Hope to make some meaningful contributions in the future.

Added myself to the list of contributors

---

i18n/index.json

I tested the change [here](https://www.reddit.com/r/DeltaLogDB3Dev2/comments/5zyuzq/deltas_awarded_in_cmv_i_think_that_foo_should_be/)

style(deltalog): add extra newline between bullet points

---

README.md
src/index.js

Not my finest hour - I think I did a commit to origin/master by accident. This is a totally new ecosystem for me. Apologies ahead of time. I learned a lot though!
I'm pretty confident in the feature, but I didn't do the full refactor necessary for this to be clean. If you need stuff changed, just let me know.

(feat(Wiki): addOrRemoveDeltaToOrFromWiki and callers)

---

src/index.js

The changes: `findDeltaLogPost` is the safe way to do a get on this particular DB 'instance', since it'll return null to the awaiting caller rather than throwing an exception, so let's use that. If we use that version to avoid the crash, then guard against nulls, we should avoid blowing up in the event something's off with the db...
Granted, `findOrMakeDeltaLogPost` should never fail to create the DB entry, I believe, so something is off there, but in the meantime this should help with uptime. @MystK, would it be possible for you to grab a dump of the current database folder on the RamNode box and upload it to somewhere accessible? Whether in the issue #225 itself or google drive or etc etc
In the meantime, this change should still be safe to push out anytime

Avoid crashing deltaLog flow when we can't find the log for a given post #225

---

src/utils.js

Accept &delta as well as !delta #229
