MystK/delta-bot-three

- delta-boards-three/index.js
Unless I'm missing something, testbots wouldn't want to read deltabot's inbox, right?  They should always read their own; for whoever runs deltabot itself, this would use the same username.
> fix: request own user's comments, rather than deltabot's

- RedditAPIDriver/index.js
- delta-boards-three/index.js
- package.json
- server.js
Take it or leave it, of course.  Running the server script, it wasn't clear to me what "75 R_API" in the console meant, and in general I think the premise of having a series of debug flags for running the deltabot script would be useful.  Perhaps the one condition currently guarded by an `ifDebug` check isn't all that useful (indeed, it didn't give me any new information apart from knowing that I got a 403 rather than a 401), but perhaps this change is worth merging anyway.
> add additional debug information, and heavily verbose --debug/npm run start-debug modes

- README.md
- RedditAPIDriver/index.js
- delta-boards-three/index.js
- package.json
- server.js
Given your comments in #51 it probably makes sense to put eslint into the documentation somewhere, and provide an alias for it, like so.  Less likely to trip folks up in that case.
Along the same lines, I fixed all the errors I saw (to be fair, I did introduce some of these in the first place)
> build: add & document `npm run test` command, for running eslint

- README.md
Per your request in #56.
Maybe someone else has documented the conventions somewhere else by now, but this is even the same link I use internally at work.  It's been around a while by now :)
> docs(contributing): link to angular commit conventions used for commit messages

- i18n.json
Prefixes USERNAME with /u/ in the confirmation comment so it links to the parent commenter's user page in addition to their wiki page. Tested on my own testing subreddit, seems to work as expected. As far as I can tell it passes all `npm run test` tests, as I didn't see any error messages.
> feat(i18n): add /u/ to username in confirm comment (#60)

- .travis.yml
- server.js
Per my comments in #52.  Someone with access to the repo settings would need to enable the webhook (see https://travis-ci.org/getting_started ), but after that every push should be covered.  You can login to travis with your github, and it's free for OSS projects, so I figure it fits pretty well overall.  By default, travis runs `npm test` for node projects ( https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Default-Test-Script ) which fits us well, at least running eslint on pull requests.  Should be trivial after that to link to the status icon on the readme, etc, I figure.  Then step two someone can figure out uploading artifacts ( https://docs.travis-ci.com/user/uploading-artifacts/ ) but running eslint on requests alone is probably worth it already.
> Travis integration

- README.md
The "How to build" section of the README was missing two important steps: running 'npm install' and 'npm run build'.
'npm install' installs required dependencies.
'npm run build' builds the project.
> docs(README): add missing steps to "How to build"

- package.json
The start script used to run supervisor with 'supervisor -w ./lib/server.js ./lib/server.js'. This caused issues when trying to call DeltaBot with command line arguments. supervisor would interpret the arguments as arguments for itself instead of arguments for the node package. As a result, DeltaBot would not run when called with arguments and would simply print supervisor's help message.
By changing the start script to 'supervisor -w ./lib/server.js -- ./lib/server.js' supervisor correctly interprets arguments passed to 'npm start' as arguments for the node package.
> fix(scripts): change supervisor command format

- server.js
If someone attempts to award a delta to OP (the poster of the thread) the bot will not accept their delta. This commit adds a command line argument '--bypass-op-check' to allow deltas to be awarded to OP. Mainly used for testing, this will be useful as it saves testers time, allowing them to use a command line argument instead of changing the code to skip over this test.
> feat(argv): add --bypass-op-check cmd line arg

- .babelrc
- delta-boards-three/index.js
- package.json
- tests/main.js
- tests/users.js
Meant to address #79.  Do note: this is completely untested in terms of running the bot.  I can't think of any reason it would fail, but that doesn't mean there isn't one.  Notably, I'm not really sure how the sidebar formatting works - if there's anything special there - or if there's legal reddit usernames like `\_somename_/` which this might spoil.
All changes outside of index.js - notably re-added devDependencies - are for a testing setup.  I wouldn't expect you to run tests on the server, so I think this would be OK?  
Either way, open for comments and complaints in terms of all these changes.  Simple enough code change, as things go, so wanted to stub out a bit of test infrastructure while I was at any change.
EDIT: would I need to update the yarn lock?  I haven't used yarn yet, …
> fix(deltaboard): ensure underscores in deltaboard are escaped, to avoid bold/italics

- src/utils.spec.js
* Line breaks on long lines in the utils.spec.js
* Tell `eslint` to ignore the camelcase `body_html`
> pass the build tests

- src/index.js
After trying this out for a while, I feel the bolding makes [Quote] stand out more than is necessary.
> fix(deltalog): Remove bold from [Quote]

- src/index.js
Fixes issue #28. There was a path in the code where it was not checked if DeltaBot already replied. It is now moved to the verifyAndAward function, which makes sure that all paths in the code must at least once check if DeltaBot has not already replied.
I also (first) took a look at the possibility of this being caused by some kind of race condition, but I could not find any problems. There is no way that DeltaBot would process the same comment again, so that can not cause it. Also, the retry system of API requests, although not perfect, seems to work as intended in my tests.
> Double delta comment

- src/delta-boards-three.js
Fixes issue #107. Was a simple problem with the time used as start and end of the week. As the current time was used as the start of the week, no deltas were collected on Monday. Also the weekly deltas would shift based on the current time.
> Weekly deltaboard bug

- src/delta-boards-three.js
- src/delta-boards-year.js
- src/index.js
Fixes issues #36 #96. Generates a yearly deltaboard for the current year and pushes those to the hidden params in the wiki. The daily/weekly/monthly process then builds the yearly board with the hidden params in the wiki.
Feedback is welcome!
> Yearly Deltaboard

- src/delta-boards-three.js
- src/delta-boards-year.js
Fix for #152. Also made the yearly deltaboard update every 3 hours instead of daily, and made the yearly deltaboard consider all relevant threads from the previous year instead of only the last week.
> fix(deltaboards): Yearly deltaboard fixes

- i18n/index.json
closes #183 
Tested [here](https://www.reddit.com/r/DeltaLogDB3Dev2/comments/60mb0i/deltas_awarded_in_hell_is_empty_and_all_the/) and [here](https://www.reddit.com/r/DeltaLogDB3Dev2/comments/62c4px/deltas_awarded_in_cmv_how_hard_it_is_that_we_have/)
I went with the less disruptive approach of baking `/?context=1` into the i18n.
This will add `/?context=1` to the awarded comment's link even when no such parent comment exists. In such a case, visiting the context-ed link [still works](https://www.reddit.com/r/changemyviewDB3Dev2/comments/62c4ky/cmv_how_hard_it_is_that_we_have_to_die/dfle08u/?context=1) without any ill effects.
> feat(deltalog):  display parent comment/context of the awarded comment

- package.json
- src/index.js
- yarn.lock
closes #189
Tested [here](https://www.reddit.com/r/DeltaLogDB3Dev2/comments/64k2jy/deltas_awarded_in_cmv_your_sister_swims_out_to/)
I'm not too sure how modules are usually handled in NodeJS/Yarn, but the below is what I did; please tell me if any of these are wrong/defy convention.
- I have added a new dependency (unescape) to `package.json`
- I have checked in an updated `yarn.lock` (that was generated by issuing a bare `yarn`)
- I placed the require near the top of `index.js`
> fix(deltalog): xml-unescape the title of deltalog entries

- i18n/index.json
- src/index.js
- src/utils.js
- src/utils.spec.js
Mostly getting comfortable and setup with running the bot again, but...here we are!  An implementation for #128
Tested in https://www.reddit.com/r/db3_wyantb/comments/6e3yqs/deltas_awarded_in_deltacomments_in_cmv_can_we_get/ (note to snorrrrlax - yes, I basically disabled every validation test that the bot checks for before awarding deltas, since I'm just changing output format and not any of the rules or anything.  I'm aware the post looks completely ridiculous, hah.  But it's formatted as you were thinking now!)
> feat(DeltaLog): aggregate deltas given for single comment by displaying awarders together

- README.md
Change to use two files, `./config/credentials/credentials.json` and `./config/config.json`.
Old one still put all config in `.config/credentials/credentials.json`
`npm test` passed.
> Change README to be consistent with yarn output

- .gitignore
- package-lock.json
- package.json
- src/db.js
- src/index.js
- src/utils.js
- yarn.lock
This is an attempt to fix both #207 and #217 
Tested this out in https://www.reddit.com/r/db3_wyantb/comments/7ojvdi/cmv_this_is_a_test_and_only_a_test_please_ignore/ - I got up to having 3 delta comments in the post, then shutdown the bot instance that was running, made the 4th comment & award, then restarted the bot...and it updated the existing sticky comment with a link to the DeltaLog post it had made earlier. Good stuff. Since that's all my tweaks are related to, I didn't really test anything outside of this area.
You can also see that the old deltalog storage method, https://www.reddit.com/r/db3_wyantb/wiki/internal , is empty.
> #207 use DB for deltalog/stickComment reliability & de-duplication & related tweaks
